CMPUT301W24T05/PlaceHolderProjectName

app/src/main/AndroidManifest.xml, app/src/main/res/drawable/baseline_camera_alt_24.xml, app/src/main/res/layout/fragment_profile_creation.xml, app/src/main/res/values/custom_style.xml
Added two newly created activities to the Manifest
added a camera icon to the drawable
=> Created Admin Page, Added a custom style to the values

app/build.gradle.kts, app/src/main/java/ca/cmput301t05/placeholder/ProfileEditActivity.java, app/src/main/java/ca/cmput301t05/placeholder/database/ProfileTable.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java
Profile class now uses `String.valueOf()` for profileID and profilePictureID. Replaced `DeviceIDManager` in `ProfileEditActivity` with `PlaceholderApp`. Upgraded Firestore dependency in `build.gradle.kts`. Changed `pushProfile` method in `ProfileTable` to use `profile.toDocument()`.
=> Merge Device UUID Branch

app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/EnterEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/res/layout/event_enterdetails.xml, app/src/main/res/values/strings.xml
maybe change the main activity a bit
=> Add event creation page

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/database/ImageTable.java, app/src/main/java/ca/cmput301t05/placeholder/events/EnterEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/events/uploadPosterActivity.java, app/src/main/res/layout/event_uploadposter.xml
capability to upload event posters
=> Upload event poster

.gitignore, app/build.gradle.kts, app/src/androidTest/java/ca/cmput301t05/placeholder/database/ProfileTableTest.java, app/src/main/java/ca/cmput301t05/placeholder/LoadingScreenActivity.java, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/database/DatabaseManager.java, app/src/main/java/ca/cmput301t05/placeholder/database/ImageTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/ProfileTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/Table.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/uploadPosterActivity.java, app/src/test/java/ca/cmput301t05/placeholder/database/ProfileTableTest.java
Refactored how ProfileTable and ImageTable reference DatabaseManager so they would be compatible with testing. Added three tests for the ProfileTable class.
=> Merge ProfileTableTests branch into main

app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/event_infor_view_and_signup.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/res/layout/event_infor_view_and_signup.xml
1. Event class, and PlaceHolderApp class implement Serializable, this is because I need to pass the event object and app object in the bundle while creating the fragment showing event details.
2. what is left to be down: get the organizer of the event, create the bundle after scanning the QR code
=> Created Event info page for attendee

app/build.gradle.kts, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/QRCodeManager.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRcodeScanner.java
Add the the following method to QRcodeManager:
1. Get the UUID from QRcode raw text
2. Test whether type is eventQRcode or infoQRcode
=> Some changes to QRcodeManager

app/src/main/java/ca/cmput301t05/placeholder/events/QRCodeManager.java
Added method that joins event in QRCodeManager
=> Updated QRCodeManager 

app/src/main/java/ca/cmput301t05/placeholder/ui/home/HomeFragment.java, app/src/main/res/navigation/mobile_navigation.xml, app/src/main/res/values/strings.xml
Buttons for Notification, Profile, and Create an Event.
=> Connecting buttons on Home Screen

app/src/main/java/ca/cmput301t05/placeholder/LoadingScreenActivity.java, app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EnterEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/UploadPosterActivity.java, app/src/main/res/layout/event_uploadposter.xml
Changed the app to have joined + hosted events inside of it, as well as have a cached event we can use to load things.
Then changed the event creation tab to account for this
=> Event profile data management fix

app/src/main/AndroidManifest.xml, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRCode.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRCodeManager.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRCodeType.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRcodeScanner.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EnterEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventSignUpActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/GenerateQRCodesActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/ViewEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/ViewQRCodesActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/event_signupevent.xml, app/src/test/java/ca/cmput301t05/placeholder/QRCodeTest.java
Linked all of them, as well as changed the QR code manager to use enums for easier retrieval of the data.
=> Linked the Qr codes to event info and event details

app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRCode.java, app/src/test/java/ca/cmput301t05/placeholder/QRCodeTest.java
First attempt at testing QR code generation
=> Qr code tests

app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/database/Collections.java, app/src/main/java/ca/cmput301t05/placeholder/database/EventTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/NotificationTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/ProfileTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/Table.java, app/src/main/java/ca/cmput301t05/placeholder/notifications/Notification.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/main/java/ca/cmput301t05/placeholder/ui/notifications/NotificationsFragment.java
Created a notifications database, as well as edited the table class to allow us to fetch multiple documents at the same time.
Also Changed notifications database to use an enum to be more safe when we define new tables.
=> Created a notifications database

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/ca/cmput301t05/placeholder/ViewPagerAdapter.java, app/src/main/java/ca/cmput301t05/placeholder/qrcode/QRCodeManager.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventMenuActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/GenerateInfoCheckinActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/ViewQRCodesActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/creation/PreviewEventActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/event_menu/PreviewEventActivity.java, app/src/main/res/drawable/baseline_share_24.xml, app/src/main/res/layout/event_generate_info_checkin.xml, app/src/main/res/layout/event_menu.xml, app/src/main/res/layout/event_preview.xml, app/src/main/res/layout/event_viewqr.xml, app/src/main/res/layout/viewqr_fragment.xml
Added the preview page and the view qr codes page with the share functionality
=> Share qr code

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/ca/cmput301t05/placeholder/Location/LocationManager.java, app/src/main/java/ca/cmput301t05/placeholder/Location/Successful_Checked_In_Activity.java, app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/res/layout/checked_in_page.xml
Created Successful_Checked_In_Activity.java with layout file: checked_in_page.xml. 
Asked for the user to allow the app to have access to the location. and successfully get the user's last known location.
What is left: implement the checkbox functionality to either share this location or not
=> Get the geolocation of the user

app/src/androidTest/java/ca/cmput301t05/placeholder/database/ProfileImageHandlerTest.java, app/src/androidTest/java/ca/cmput301t05/placeholder/profile/ProfileImageGeneratorTest.java, app/src/main/java/ca/cmput301t05/placeholder/InitialSetupActivity.java, app/src/main/java/ca/cmput301t05/placeholder/LoadingScreenActivity.java, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ProfileEditActivity.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/BaseImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/EventPosterImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/ProfileImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/main/java/ca/cmput301t05/placeholder/profile/ProfileImageGenerator.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventDetailsDialogFragment.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventMenuActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventSignUpActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/ViewEventDetailsActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/creation/PreviewEventActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/creation/UploadPosterActivity.java, app/src/main/res/layout/fragment_profile_creation.xml
Not ready to merge yet, just want to make sure that everything builds correctly
=> Reworked Image Handling and Automatically Generate Profile Image

app/src/main/java/ca/cmput301t05/placeholder/Location/Successful_Checked_In_Activity.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/ui/codescanner/QRCodeScannerActivity.java, app/src/main/res/layout/checked_in_page.xml
1. Wait for 3 seconds and automatically Direct the user after they do not allow permission to the event details page 
2. Only when you allow permission, then when you choose to share location 
3. Add a method in Event: Reach Maximum capacity, return false if Max is reached; Use this method to check if max capacity is reached, if it is reached, go back to the home page directly
4. Changed the method checkIn in Event class, passed in the longitude and latitude as well, changed the type of the attendees to HashMap<String, HashMap<String, Double>>
5. When user do not check the checkbox to share location, or do not allow permission to share location, longitude and latitude both as NULL will be inserted into the Event document
The document looks like this:
=> Upload Geo location to the database

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventDetailsDialogFragment.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventMenuActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/organizer_info/AttendanceViewAdapter.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/organizer_info/ViewAttendeeCheckinActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/attendee_checkin_item.xml, app/src/main/res/layout/view_attendee_checkin.xml, app/src/main/res/values/strings.xml
To check how many times a person attended your event just click on their name.
=> View Attendee check-ins

app/src/main/java/ca/cmput301t05/placeholder/LoadingScreenActivity.java, app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/notifications/PushNotification.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventDetailsDialogFragment.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventSignUpActivity.java
Added another list of event IDs to each profile entry and the respective code implementation to support it. There is a new hashmap loaded into PlaceholderApp service called 'interestedEvents' that contains those events.
=> Add "Mark event as interested" functionality to profile and app service

app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/ProfileEditActivity.java, app/src/main/java/ca/cmput301t05/placeholder/database/ImageDetails/ImageDetails.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/BaseImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/EventPosterImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/ProfileImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/tables/ImageDetailTable.java, app/src/main/java/ca/cmput301t05/placeholder/database/tables/Table.java, app/src/main/java/ca/cmput301t05/placeholder/database/utils/Collections.java, app/src/test/java/ca/cmput301t05/placeholder/ProfileImageHandlerTest.java
When a user uploads a picture we send it to the database with a image details object in the firebase database. This is so we can query multiple documents by uploaded date later on
=> Added Image Details database

app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventSignUpActivity.java
[Issue #158](https://github.com/CMPUT301W24T05/PlaceHolderProjectName/issues/158)
Signing up to an event:
1. In Event Class, added getter method for attributes: ArrayList<String> registeredUsers; updated fromDocument and toDocument method in Event Class; Added userSignup(Profile user) where we check if the user has already signed up for an event or not, if already signed up, return false
2. In EventSignupActivity.java, in the handleEventButton method, implement the functionalty that user can sign up for an event, if an user already signed up, take it back to the previous page automatically after 3 seconds
3. The database looks like this:
4. Created a new method in profile document, when a user sign up for a event (click on Interested button), not only profileID added to the event table, …
=> Get registered user

app/build.gradle.kts, app/src/main/java/ca/cmput301t05/placeholder/database/ImageDetails/ImageDetails.java, app/src/main/java/ca/cmput301t05/placeholder/database/tables/ImageDetailTable.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/ViewAllImagesAdapter.java, app/src/main/res/layout/admin_image_card.xml, app/src/main/res/layout/admin_view_image_page.xml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
All pictures are spaced properly and deletion works (except for one event which was made using the old system)
Closes #13 
Closes #10
=> Admin browse image functionality

app/src/main/java/ca/cmput301t05/placeholder/ProfileEditActivity.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/BaseImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/EventPosterImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/database/images/ProfileImageHandler.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/profile/Profile.java, app/src/test/java/ca/cmput301t05/placeholder/ProfileImageHandlerTest.java
Added a callback to image deletion and now our deletion functions also update the specified event/profile in the database
=> Changed how we remove profile/poster pics

app/src/main/java/ca/cmput301t05/placeholder/Location/Successful_Checked_In_Activity.java
I added a method in the Successful_checked_in_Activity.java (after scanning the QR code) to check if the maximum is reached, if it is reached, it will show a message and go back to the previous page,
=> When check in, Check if Max capacity is reached or not

app/src/main/java/ca/cmput301t05/placeholder/database/tables/EventTable.java, app/src/main/java/ca/cmput301t05/placeholder/events/Event.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminEventAdapter.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminEventFragment.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminHomeActivity.java, app/src/main/res/layout/admin_event_card.xml
closes #11 
closes #8 
The admin page is now done.
However it is very very ugly! It needs some help to look pretty, some extra time to help out and make it look good would be appreciated!
=> 12 us 040501 be able to browse profiles

app/src/main/java/ca/cmput301t05/placeholder/events/EventAdapter.java, app/src/main/res/drawable/liked_heart.xml, app/src/main/res/layout/event_card_hosted.xml, app/src/main/res/values/custom_style.xml
Heart means the number of registered, and the human figure is attended/Max_capacity.
1. Differentiate between hostedEvent layout and joined event layout. Added a conditional statement in the EventAdpater.java
2. The Layout I created is event_card_hosted.xml
2. Created a HostedEventCardViewHolder (extend EventCardViewHolder) to add some statistics and the poster image
=> Created Organized event card (statistics)

app/src/main/java/ca/cmput301t05/placeholder/MainActivity.java, app/src/main/java/ca/cmput301t05/placeholder/ui/events/EventMenuActivity.java, app/src/main/res/layout/event_menu_updated.xml, app/src/test/java/ca/cmput301t05/placeholder/QRCodeTest.java
Fixed bug for tablet sizes and some photos breaking formatting.
=> UI improvement

app/src/main/res/drawable/baseline_attendee_black.xml, app/src/main/res/layout/event_card_hosted.xml, app/src/main/res/layout/event_menu_updated.xml, app/src/main/res/layout/event_organized.xml, app/src/main/res/layout/profile_page_updated.xml
=> Fix a couple of UI stuff

app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminEventAdapter.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminEventFragment.java, app/src/main/java/ca/cmput301t05/placeholder/ui/admin/AdminProfilesAdapter.java, app/src/main/res/drawable/baseline_analytics_24.xml, app/src/main/res/layout/admin_event_card.xml, app/src/main/res/layout/admin_mainpage.xml, app/src/main/res/layout/admin_mainpage_fragment.xml, app/src/main/res/layout/event_vieweventdetails.xml, app/src/main/res/layout/profile_card.xml
modify the admin page, change the layout a bit, and allow clicking of an event (pop-up window appears)
=> Modify admin page

app/src/main/java/ca/cmput301t05/placeholder/LoadingScreenActivity.java, app/src/main/java/ca/cmput301t05/placeholder/PlaceholderApp.java, app/src/main/java/ca/cmput301t05/placeholder/notifications/UserNotificationAdapter.java, app/src/main/java/ca/cmput301t05/placeholder/ui/notifications/UserNotificationFragment.java, app/src/main/java/ca/cmput301t05/placeholder/utils/CompareByDate.java, app/src/main/java/ca/cmput301t05/placeholder/utils/HoldNotificationToEvent.java, build.gradle.kts
closes 210
closes 136
Finally got the user notification adapter to work properly, so hopefully this is functional for everyone
=> 136 create new notification adapter for users
